import { ServiceItem, OfficeLocation, IndustryBulletin } from '../types';

export const CORVANE_INFO = {
  legalName: 'Corvane Freight Group',
  tradingName: 'Corvane Freight',
  establishedCredentials: 'Over 20 years’ experience across 3 continents',
  abn: 'Available upon request',
  generalEmail: 'aleehanajeeb.work@gmail.com',
  officialTrackingUrl: 'https://example.com/track',
  tagline: 'Australian Freight Forwarding with Global Precision',
  positioning: 'Specialists in domestic and international freight forwarding, customs clearance, road transport, and end-to-end 3PL solutions.',
};

export const CORVANE_METRICS = [
  { value: '20+', label: 'Years Proven Experience', detail: 'Serving Australian importers and exporters' },
  { value: '3', label: 'Continents Operational Reach', detail: 'Direct agency networks across Asia, Americas, Europe' },
  { value: 'EDI', label: 'Direct Border Force Link', detail: 'Computerized rapid electronic customs clearance' },
  { value: '2', label: 'Strategic Australian Hubs', detail: 'Melbourne Headquarters & Sydney Commercial Office' },
];

export const CORVANE_SERVICES: ServiceItem[] = [
  {
    id: 'air-freight',
    number: '01',
    title: 'Air Freight',
    tagline: 'Fast international air freight, tracked from pickup to landing',
    category: 'Air',
    summary: 'Fast international shipping for urgent or high-value cargo, with tracking from pickup to arrival.',
    description: 'When cargo cannot wait for a vessel, we put it on a plane. We book direct and consolidated air freight on major airline networks, and you can follow your shipment from departure to touchdown. Best for perishable, urgent, or high-value consignments.',
    capabilities: [
      'General airfreight import and export management',
      'Cross-trade freight management across global routes',
      'Charter cargo solutions for out-of-gauge and urgent freight',
      'Door-to-airport and door-to-door delivery',
      'Dangerous Goods (IATA certified) and temperature-monitored consignments',
      'Airport tarmac supervision and expedited airline terminal transfers',
    ],
    equipment: [
      'Lower deck ULD containers (LD3, LD7, LD9)',
      'Main deck air freight pallets and contour nets',
      'Temperature-controlled Envirotainers for pharmaceuticals and perishables',
      'Heavy-lift freighter aircraft cargo capacity',
    ],
    cargoHandled: [
      'High-value electronics and computing parts',
      'Automotive and aviation spare components (AOG)',
      'Time-critical machinery parts',
      'Pharmaceutical and medical equipment',
      'Urgent commercial manufacturing samples',
    ],
    complianceNotes: 'Full compliance with IATA Dangerous Goods Regulations, Australian Department of Home Affairs, and international aviation security frameworks.',
    transitAdvantage: 'Fastest global transit: 1–4 days internationally, with priority same-day domestic line connections.',
    image: '/images/air-freight.webp',
  },
  {
    id: 'sea-freight',
    number: '02',
    title: 'Sea Freight',
    tagline: 'Cost-effective ocean freight on weekly sailings to major trade lanes',
    category: 'Ocean',
    summary: 'Full and shared container shipping on weekly sailings. The cheapest way to move large volumes.',
    description: 'For high-volume cargo, sea is the most cost-effective way to ship, typically three to five times cheaper than air. Containers carry heavy payloads (up to 28+ tonnes depending on container type and Australian road limits) with far lower emissions per tonne-kilometre. Transit takes longer than air, and we give you realistic times upfront.',
    capabilities: [
      'Full Container Load (FCL) shipping (20ft, 40ft, 40ft High Cube)',
      'Less than Container Load (LCL) consolidation and buyer de-consolidation',
      'Direct shipping line relationships offering priority space allocations',
      'Reefer container management for temperature-sensitive cargo',
      'Out of Gauge (OOG) container options (Open Tops & Flat Racks)',
      'Port-to-port or full door delivery with inland transport',
    ],
    equipment: [
      '20’ & 40’ General Purpose (GP) steel containers',
      '40’ High Cube (HC) containers (76.2 m³ capacity)',
      '20’ & 40’ Open Top (OT) with removable tarpaulin',
      '20’ & 40’ Flat Rack (FR) for over-dimensional freight',
      'Reefer refrigerated containers (-25°C to +25°C temperature monitoring)',
    ],
    cargoHandled: [
      'Consumer goods, retail merchandise, and apparel',
      'Building materials, timber, tiles, and steel coils',
      'Raw industrial commodities and manufacturing inputs',
      'Commercial furniture, whitegoods, and electrical appliances',
      'Automotive parts, agricultural tools, and machinery',
    ],
    complianceNotes: 'Verified Gross Mass (VGM) compliance under SOLAS regulations and Australian Border Force reporting mandates.',
    transitAdvantage: 'Maximum cost efficiency for high volume freight with scheduled weekly departures to/from Melbourne, Sydney, Brisbane, and Fremantle.',
    image: '/images/sea-freight.webp',
  },
  {
    id: 'project-cargo',
    number: '03',
    title: 'Project Cargo',
    tagline: 'Heavy and out-of-gauge cargo, planned properly from day one',
    category: 'Specialised',
    summary: 'Heavy machinery and oversized loads, planned route by route and delivered to site on schedule.',
    description: 'Machinery and oversized loads need planning, not guesswork. We engineer the route, check bridge and road clearances, arrange cranes and rigging, and coordinate sea, port, and road transport so your equipment arrives on schedule and in one piece.',
    capabilities: [
      'Route surveys and road clearance checks before anything moves',
      'Sea charters and heavy road haulage combined into one plan',
      'Mining, oil & gas, and renewable infrastructure project management',
      'Heavy-lift crane rigging, stevedoring, and marine vessel chartering',
      'Police and electrical authority escort coordination for over-dimensional cargo',
      'Our own supervisor on site through discharge',
    ],
    equipment: [
      'Multi-axle hydraulic platform trailers (modular SPMTs)',
      'Heavy crawler cranes and gantry lifting jacks',
      'Custom ocean barge and heavy-lift gearless vessels',
      'Customized heavy timber dunnage and certified lashing systems',
    ],
    cargoHandled: [
      'Wind turbine blades, nacelles, and tower sections',
      'Mining excavators, dump trucks, and crushing plants',
      'Transformers, turbines, pressure vessels, and boilers',
      'Pre-fabricated industrial plant modules and structural steelwork',
    ],
    complianceNotes: 'Australian State Road Authority oversize/overmass permits and full maritime safety engineering certification.',
    transitAdvantage: 'We commit to site delivery dates and plan backwards from them.',
    image: '/images/project-cargo.webp',
  },
  {
    id: 'break-bulk',
    number: '04',
    title: 'Break Bulk',
    tagline: 'Oversized, non-containerised cargo shipped on the right vessel',
    category: 'Specialised',
    summary: 'Cargo too big for a container, shipped loose on the right vessel and discharged safely.',
    description: 'Cargo that will not fit in a container needs the right ship and the right plan. We arrange stowage plans, marine surveyor checks, and port handling so your goods are loaded safely, secured under deck or on hatch covers, and discharged without damage.',
    capabilities: [
      'Chartering and part-cargo bookings with leading break bulk ocean carriers',
      'Wharf-side direct discharge from vessel tackle onto heavy road transport',
      'Stowage planning and certified lashing calculations',
      'Independent marine surveyor pre-shipment inspections and hold condition reports',
      'Stevedoring management at Port of Melbourne, Geelong, Port Kembla, and Newcastle',
    ],
    equipment: [
      'Harbour mobile cranes and vessel shipboard heavy derricks',
      'Spreader beams, certified heavy-duty wire slings, and grommets',
      'Specialist heavy-duty flatbed trailers and extendable trombone trailers',
    ],
    cargoHandled: [
      'Heavy industrial machinery and factory production lines',
      'Structural steel beams, pipe bundles, and plate steel',
      'Boats, luxury motor yachts, and maritime vessels',
      'Agricultural tractors, harvesters, and earthmoving loaders',
    ],
    complianceNotes: 'Compliant with IMO Code of Safe Practice for Cargo Stowage and Securing (CSS Code).',
    transitAdvantage: 'Direct berthing and discharge without intermediate container unpacking steps.',
    image: '/images/break-bulk.webp',
  },
  {
    id: 'transport',
    number: '05',
    title: 'Transport',
    tagline: 'Reliable container cartage and interstate linehaul across Australia',
    category: 'Land & Clearance',
    summary: 'Container cartage from Port of Melbourne and Port Botany, plus interstate linehaul across Australia.',
    description: 'We connect ports, airports, warehouses, and your customer’s door. Our fleet of prime movers, skel trailers, sideloaders, and tautliners handles wharf cartage, container unpacks, and time-slotted metropolitan and interstate linehaul.',
    capabilities: [
      'Wharf cartage directly from Patrick, DP World, and VICT terminals',
      'Sideloader container placement directly onto client hardstands',
      'Interstate linehaul across Melbourne, Sydney, Brisbane, and Adelaide',
      'Over-dimensional and heavy haulage with pilot escort coordination',
      'Strict time-slot delivery management (VBS / Containerchain coordination)',
      'Dangerous Goods (DG) compliant vehicles and certified drivers',
    ],
    equipment: [
      'Modern prime movers meeting Euro 5/6 emission criteria',
      'Standard 40’ and 20’ skeletal container trailers',
      'Heavy-capacity sideloaders (swing-lifters) for ground-level drop-offs',
      'Drop-deck and low-loader trailers for over-height cargo',
      'Tautliners and mezzanine-deck trailers for palletised distribution',
    ],
    cargoHandled: [
      'Shipping containers (20ft, 40ft, High Cube, Open Top)',
      'Palletised commercial freight and FMCG goods',
      'Industrial machinery, structural steel, and pre-cast concrete',
      'Packaged dangerous goods and hazardous chemical drums',
    ],
    complianceNotes: 'Adherence to National Heavy Vehicle Regulator (NHVR) Chain of Responsibility (CoR) laws.',
    transitAdvantage: 'Dedicated wharf slots and direct depot shunting to eliminate port dwell delays.',
    image: '/images/transport.webp',
  },
  {
    id: 'export',
    number: '06',
    title: 'Export',
    tagline: 'From your dock to overseas buyers, handled end to end',
    category: 'Land & Clearance',
    summary: 'We handle the paperwork, bookings, and shipping that take Australian goods to overseas buyers.',
    description: 'We ship Australian goods worldwide. Through long-standing carrier relationships and a worldwide agent network, we handle everything from packing and inland collection to export permits, consolidation, and customs clearance at the destination.',
    capabilities: [
      'Global ocean and airfreight export space bookings and negotiation',
      'Preparation of Export Declarations (EDN) through the Australian Border Force',
      'Certificates of Origin, Commercial Invoices, and Packing List certification',
      'DAFF phytosanitary and export health certificate documentation',
      'Export container packing, fumigation, and wharf lodgement (PRA / EDN)',
      'Letter of Credit (L/C) compliance checking and consular legalisation',
    ],
    equipment: [
      'Certified export-compliant container packaging and timber (ISPM 15)',
      'Desiccant and moisture barrier systems for ocean voyages',
      'Container GPS security seals and temperature data loggers',
    ],
    cargoHandled: [
      'Australian agricultural produce, grains, and specialty foods',
      'Manufactured Australian industrial equipment and consumer products',
      'High-grade timber, minerals, and specialised construction materials',
      'Automotive and aviation exports to Asia, Europe, and the Americas',
    ],
    complianceNotes: 'Strict adherence to Australian Export Control Act 2020 and destination country import protocols.',
    transitAdvantage: 'Predictable vessel cut-offs, rapid documentation release, and guaranteed carrier slot allocations.',
    image: '/images/export.webp',
  },
  {
    id: 'customs-clearance',
    number: '07',
    title: 'Customs Clearance',
    tagline: 'Direct computerised EDI link to Australian Customs for fast clearance',
    category: 'Land & Clearance',
    summary: 'Licensed brokers clear your cargo through Australian border, quickly and by the book.',
    description: 'Our licensed customs brokers lodge declarations directly into the Integrated Cargo System (ICS) through an EDI link with the Department of Home Affairs and Australian Border Force. Cargo clears quickly, which means no demurrage or port storage surprises.',
    capabilities: [
      'Direct computerised EDI link to Australian Customs / Border Force',
      'Electronic lodgement of Import Declarations (N10) and Self-Assessed Clearances',
      'Tariff classification and concession order (TCO) applications',
      'Department of Agriculture, Fisheries and Forestry (DAFF/AQIS) biosecurity compliance',
      'Free Trade Agreement (FTA) certificate audit and duty reduction strategies',
      'Temporary importations (Carnets) and anti-dumping review',
    ],
    equipment: [
      'Dedicated Integrated Cargo System (ICS) EDI terminal',
      'Automated Customs cargo status tracking software',
      'Biosecurity documentation and quarantine treatment auditing protocols',
    ],
    cargoHandled: [
      'All commercial imports and exports subject to Australian border control',
      'Agricultural, timber, and biological items subject to DAFF inspection',
      'Chemical, hazardous, and regulated commercial substances',
      'Capital equipment claiming tariff duty exemptions',
    ],
    complianceNotes: 'Zero-tolerance compliance with Australian Customs Act 1901 and Biosecurity Act 2015 standards.',
    transitAdvantage: 'Pre-clearance prior to vessel arrival at Australian berths, preventing wharf storage penalties.',
    image: '/images/customs-clearance.webp',
  },
  {
    id: '3pl',
    number: '08',
    title: '3PL',
    tagline: 'Storage, pick and pack, and fast dispatch from our Port Melbourne warehouse',
    category: 'Land & Clearance',
    summary: 'Warehousing in Port Melbourne with container unpack, secure storage, pick and pack, and dispatch.',
    description: 'Our Port Melbourne warehouse is minutes from the container terminals and the freeway network. We destuff containers, store pallets securely, pick and pack orders, and dispatch to your customers, with live inventory visibility so you always know your stock.',
    capabilities: [
      'Container destuffing, palletising, slip-sheeting, and stretch-wrapping',
      'Secure racked pallet storage and block-stack floor space',
      'Pick, pack, and barcode labelling for retail and industrial distribution',
      'Real-time Warehouse Management System (WMS) inventory visibility',
      'Cross-docking for immediate transhipment to interstate linehaul',
      'Reverse logistics, customer returns inspection, and disposal management',
    ],
    equipment: [
      'High-reach electric forklifts and counterbalance trucks',
      'Heavy-duty narrow-aisle racking systems',
      'Container loading docks and hydraulic dock levellers',
      'Automated pallet wrapping and dimensioning stations',
    ],
    cargoHandled: [
      'Imported consumer goods, electronics, and home decor',
      'Industrial spare parts, hardware, and engineering fittings',
      'Fast-Moving Consumer Goods (FMCG) and dry grocery items',
      'Automotive aftermarket accessories and tyres',
    ],
    complianceNotes: 'Regulated Australian security protocols with 24/7 CCTV surveillance and fire suppression systems.',
    transitAdvantage: 'Located minutes from Melbourne’s freeway network and container terminals for same-day dispatch.',
    image: '/images/3pl.webp', // Warehouse photo
  },
];

export const CORVANE_OFFICES: OfficeLocation[] = [
  {
    id: 'melbourne-hq',
    city: 'Melbourne',
    role: 'Corporate Headquarters & Operations Center',
    address: 'Unit 4, 18 Freight Way',
    suburb: 'Port Melbourne',
    state: 'VIC',
    postcode: '3207',
    phone: '+61355501234',
    phoneFormatted: '+61 3 5550 1234',
    mobile: '+61491570156',
    mobileFormatted: '+61 491 570 156',
    email: 'aleehanajeeb.work@gmail.com',
    hours: 'Monday – Friday: 08:30 – 17:30 AEST',
    portProximity: 'Minutes from the Port of Melbourne container terminals; immediate access to the West Gate Freeway.',
    description: 'Our primary operational and dispatch headquarters managing air freight, ocean vessel bookings, customs EDI lodgements, and Victorian 3PL warehousing.',
  },
  {
    id: 'sydney-office',
    city: 'Sydney',
    role: 'Commercial & Freight Management Office',
    address: 'Level 9, 25 Cargo Lane',
    suburb: 'Sydney',
    state: 'NSW',
    postcode: '2000',
    phone: '+61255500187',
    phoneFormatted: '+61 2 5550 0187',
    email: 'aleehanajeeb.work@gmail.com',
    hours: 'Monday – Friday: 08:30 – 17:30 AEST',
    portProximity: 'Direct arterial connection to Port Botany container terminals and Sydney Kingsford Smith Airport.',
    description: 'Dedicated commercial freight operations providing New South Wales cargo clearance, client account management, and East Coast logistics coordination.',
  },
];

export const CORVANE_TRADE_LANES = [
  {
    corridor: 'Australia ⇄ East Asia & China',
    ports: 'Port of Melbourne / Port Botany ⇄ Shanghai, Ningbo, Shenzhen, Qingdao',
    modes: 'Ocean (14–22 days) | Air (1–3 days)',
    description: 'High-frequency trade lane for manufactured goods, electronics, industrial machinery, and raw material exports.',
    transitTime: '14–22 Days Ocean',
  },
  {
    corridor: 'Australia ⇄ Southeast Asia',
    ports: 'Melbourne / Sydney ⇄ Singapore, Port Klang, Tanjung Pelepas, Jakarta',
    modes: 'Ocean (11–18 days) | Air (1–2 days)',
    description: 'Strategic regional transhipment hub corridor connecting Australian businesses to ASEAN manufacturing clusters.',
    transitTime: '11–18 Days Ocean',
  },
  {
    corridor: 'Australia ⇄ North America',
    ports: 'Melbourne / Sydney / Brisbane ⇄ Los Angeles, Long Beach, New York, Vancouver',
    modes: 'Ocean (22–32 days) | Air (2–4 days)',
    description: 'Heavy machinery, automotive parts, aerospace, and high-value commercial trade routes.',
    transitTime: '22–32 Days Ocean',
  },
  {
    corridor: 'Australia ⇄ Europe & UK',
    ports: 'Melbourne / Fremantle ⇄ Rotterdam, Antwerp, Hamburg, Felixstowe',
    modes: 'Ocean (34–45 days) | Air (2–4 days)',
    description: 'Premium capital equipment, precision engineering, consumer luxury goods, and pharmaceutical supply chains.',
    transitTime: '34–45 Days Ocean',
  },
];

export const CORVANE_BULLETINS: IndustryBulletin[] = [
  {
    id: 'dp-world-update',
    date: 'Recent Advisory',
    category: 'Waterfront',
    title: 'Australian Terminal & DP World Waterfront Operations Notice',
    excerpt: 'Operational review of terminal throughput, vessel berthing schedules, and road transport slot availability across Melbourne and Sydney.',
    readTime: '3 min read',
    content: 'Corvane Freight continuously tracks terminal operations at DP World, Patrick Terminals, and VICT. Our direct electronic vehicle booking systems ensure our fleet secures primary slots to prevent detention and demurrage impacts on client cargo.',
  },
  {
    id: 'bmsb-measures',
    date: 'Seasonal Notice',
    category: 'Biosecurity',
    title: 'Department of Agriculture (DAFF) BMSB Seasonal Biosecurity Protocols',
    excerpt: 'Mandatory offshore treatment requirements and documentation audits for target risk goods entering Australia.',
    readTime: '4 min read',
    content: 'All target high-risk goods manufactured in or shipped from target risk countries during the active season require approved offshore treatment. Our licensed customs brokers verify documentation prior to port departure.',
  },
  {
    id: 'maritime-transit',
    date: 'Trade Advisory',
    category: 'Trade Advisory',
    title: 'Global Maritime Routing & Capacity Allocation Overview',
    excerpt: 'Analysis of major shipping alliance schedules, bunker adjustment factors (BAF), and equipment availability for Australian trades.',
    readTime: '3 min read',
    content: 'Global ocean carrier alliances continue to adjust vessel routing. Corvane maintains multi-carrier contractual relationships to safeguard space allocations and mitigate sudden schedule deviations.',
  },
];
